spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sad?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop